
require("tuladhp.plugins-setup")
require("tuladhp.core.options")
require("tuladhp.core.keymaps")
require("tuladhp.core.colorscheme")
require("tuladhp.plugins.comment")
require("tuladhp.plugins.nvim-tree")
require("tuladhp.plugins.lualine")
require("tuladhp.plugins.telescope")
require("tuladhp.plugins.nvim-cmp")
require("tuladhp.plugins.lsp.mason")
require("tuladhp.plugins.lsp.lspsaga")
require("tuladhp.plugins.lsp.lspconfig")
require("tuladhp.plugins.lsp.null-ls")
require("tuladhp.plugins.autopairs")
require("tuladhp.plugins.treesitter")
require("tuladhp.plugins.gitsigns")
